[build]
  base    = "create-react-app-master"
  publish = "build"
  command = "yarn build"
  

# A redirect rule with all the supported properties
[[redirects]]
  from = "/"
  to = "/create-react-app"
